title: 'Daniil Developer Bolg'
description: 'A site created by Spress'
logo: spresso-logo.png
url: ''
parsedown_actived: true
comments:
    enabled: false
    disqus_shortname: ''
author:
    name: 'Daniil Developer'
    twitter: daniildeveloper
    github: 'https://github.com/daniildeveloper/devblog'
    bitbucket: null
    facebook: null
    linkedin: null
    gplus: null
    youtube: null
collections:
    posts: { output: true }
    projects: { output: true }
feed:
    max_item: 10
open_graph:
    locale: en_US
code_highlight: true
google_verify: null
bing_verify: null
top_menu:
    - { name: Home, url: / }
    - { name: Projects, url: /projects }
bottom_menu:
    - { name: 'Go to the Spresso theme webpage', url: 'https://github.com/yosymfony/Spress-theme-spresso' }
themes:
    name: spress/spress-theme-spresso
